name: solvcon_devenv
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: main build
        run: |
          source ${GITHUB_WORKSPACE}/scripts/init
          devenv add test
          devenv use test
          devenv build openssl
          devenv build zlib
          devenv build python
          devenv build cython
          devenv build openblas
          devenv build numpy
          devenv build pybind11
          devenv build modmesh
