#!/usr/bin/env bash

set -e

pkgname=expat
pkgver=${VERSION:-2.6.2}
pkgfull=$pkgname-$pkgver
pkgfn=$pkgfull.tar.xz
pkgurl=https://github.com/libexpat/libexpat/releases/download/R_$(echo ${pkgver} | sed 's/\./_/g')/expat-${pkgver}.tar.xz

download_md5 $pkgfn $pkgurl 0cb75c8feb842c0794ba89666b762a2d

mkdir -p ${DEVENVCURRENTROOT}/src
pushd ${DEVENVCURRENTROOT}/src > /dev/null
  tar xf ${DEVENVDLROOT}/$pkgfn
popd > /dev/null

cfgcmd=("./configure")
cfgcmd+=("--prefix=${DEVENVPREFIX}")

pushd ${DEVENVCURRENTROOT}/src/${pkgfull} > /dev/null

  buildcmd configure.log "${cfgcmd[@]}"
  buildcmd make.log make -j ${NP}
  buildcmd install.log make install

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
